# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  # Get version info from app/build.gradle.kts
  def android_version_info
    gradle_file = File.read("../app/build.gradle.kts")
    version_code = gradle_file[/versionCode\s*=\s*(\d+)/, 1]
    version_name = gradle_file[/versionName\s*=\s*"([^"]+)"/, 1]
    {
      "Version Code" => version_code || "N/A",
      "Version Name" => version_name || "N/A"
    }
  end

  desc "Upload STAGING APK to Firebase"
    lane :staging_to_firebase do
      begin
        gradle(task: "assembleStagingRelease")

        commit_message = sh("git log -1 --format=%s").strip

        firebase_app_distribution(
          app: "1:569274712516:android:782915705e34a05ebca491",
          groups: "firebase-testers",
          release_notes: commit_message
        )

#         slack(
#           message: "✅ STAGING APK uploaded to *Firebase App Distribution*",
#           success: true,
#           payload: android_version_info,
#           slack_url: ENV["WEBHOOK_URL"]
#         )
#       rescue => ex
#         slack(
#           message: "❌ STAGING Firebase upload failed",
#           success: false,
#           payload: android_version_info.merge("Error" => ex.message),
#           slack_url: ENV["WEBHOOK_URL"]
#         )
#         raise ex
      end
    end

  desc "Upload prod aab to play store"
  lane :upload_prod_to_play_store do
    begin
      build_android_app(task: "bundleProdRelease")
      json_key_path = ENV['GOOGLE_APPLICATION_CREDENTIALS']

      upload_to_play_store(
        package_name: 'com.app.androidcompose.prod',
        track: 'internal',
        json_key: json_key_path,
        skip_upload_apk: 'true'
      )

      slack(
        message: "✅ PROD AAB uploaded to *Play Store (internal)*",
        success: true,
        payload: android_version_info,
        slack_url: ENV["WEBHOOK_URL"]
      )
    rescue => ex
      slack(
        message: "❌ PROD Play Store upload failed",
        success: false,
        payload: android_version_info.merge("Error" => ex.message),
        slack_url: ENV["WEBHOOK_URL"]
      )
      raise ex
    end
  end
end